// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type GooseDbVersion struct {
	ID        int32        `json:"id"`
	VersionID int64        `json:"version_id"`
	IsApplied bool         `json:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp"`
}
